{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.insert(0,'..')\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import unittest\n",
    "import numpy as np\n",
    "\n",
    "from bayes.parameters import ParameterList\n",
    "from bayes.inference_problem import VariationalBayesProblem, ModelErrorInterface\n",
    "from bayes.noise import UncorrelatedNoiseModel\n",
    "\n",
    "import arviz as az\n",
    "import torch\n",
    "import pyro\n",
    "import pyro.distributions as dist\n",
    "import pyro.poutine as poutine\n",
    "from pyro.infer import MCMC, NUTS, Predictive"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Sensor:\n",
    "    def __init__(self, name, shape=(1, 1)):\n",
    "        self.name = name\n",
    "        self.shape = shape\n",
    "\n",
    "    def __repr__(self):\n",
    "        return f\"{self.name} {self.shape}\"\n",
    "\n",
    "\n",
    "class MySensor(Sensor):\n",
    "    def __init__(self, name, position):\n",
    "        super().__init__(name, shape=(1, 1))\n",
    "        self.position = position\n",
    "\n",
    "\n",
    "class MyForwardModel:\n",
    "    def __call__(self, parameter_list, sensors, time_steps):\n",
    "        \"\"\"\n",
    "        evaluates \n",
    "            fw(x, t) = A * x + B * t\n",
    "        \"\"\"\n",
    "        A = parameter_list[\"A\"]\n",
    "        B = parameter_list[\"B\"]\n",
    "\n",
    "        result = {}\n",
    "        for sensor in sensors:\n",
    "            result[sensor] = A * sensor.position + B * time_steps\n",
    "        return result\n",
    "\n",
    "    def parameter_list(self):\n",
    "        p = ParameterList()\n",
    "        p.define(\"A\", None)\n",
    "        p.define(\"B\", None)\n",
    "        return p\n",
    "\n",
    "\n",
    "class MyModelError(ModelErrorInterface):\n",
    "    def __init__(self, fw, data):\n",
    "        self._fw = fw\n",
    "        self._ts, self._sensor_data = data\n",
    "        self.parameter_list = fw.parameter_list()\n",
    "\n",
    "    def __call__(self):\n",
    "        sensors = list(self._sensor_data.keys())\n",
    "        model_response = self._fw(self.parameter_list, sensors, self._ts)\n",
    "        error = {}\n",
    "        for sensor in sensors:\n",
    "            error[sensor] = model_response[sensor] - self._sensor_data[sensor]\n",
    "        return error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "class PytorchProblem(VariationalBayesProblem):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "\n",
    "    def posterior_pytorch_model(self):\n",
    "        #sampled_parameters = ParamStoreDict()\n",
    "        sampled_parameters = {}\n",
    "\n",
    "        for name, (mean, sd) in self.prm_prior.items():\n",
    "            # idx = problem.latent[name].start_idx\n",
    "            assert self.latent[name].N == 1  # vector parameters not yet supported!\n",
    "            sampled_parameters[name] = pyro.sample(name, dist.Normal(mean, sd))\n",
    "\n",
    "        for name, gamma in self.noise_prior.items():\n",
    "            # idx = problem.latent[name].start_idx\n",
    "            shape, scale = gamma.shape, gamma.scale\n",
    "            alpha, beta = shape, 1.0 / scale\n",
    "            # check for Gamma and Inverse Gamma\n",
    "            sampled_noise_precision = pyro.sample(name, dist.Gamma(alpha, beta))\n",
    "            self.noise_models[name].parameter_list['precision'] = sampled_noise_precision.numpy()\n",
    "\n",
    "        for noise_key, noise_term in self.noise_models.items():\n",
    "            pyro.sample(noise_key + \"_latent\",\n",
    "                        dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
    "                        noise_term.parameter_list['precision']),\n",
    "                        obs=torch.zeros(len(vector)))\n",
    "        return\n",
    "\n",
    "    def wrapper_function(self, sampled_parameters, noise_key):\n",
    "        for name, value in sampled_parameters.items():\n",
    "             self.latent[name].set_value(value)\n",
    "\n",
    "        # compute raw model error using the samples parameters, this is now done for each noise term separately\n",
    "        raw_me = {}\n",
    "        for key, me in self.model_errors.items():\n",
    "            raw_me[key] = me()\n",
    "        #print(me)\n",
    "        vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
    "        return torch.from_numpy(vector)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "temp ={}\n",
    "for a, (b,c) in problem.prm_prior.items():\n",
    "    temp[a] = pyro.sample(a,dist.Normal(b,c))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "noise0 Gamma with \n",
      " └── mean: (2.7777777777777772, 9)\n",
      "noise1 Gamma with \n",
      " └── mean: (0.6944444444444443, 9)\n"
     ]
    }
   ],
   "source": [
    "for name, gamma in problem.noise_prior.items():\n",
    "    print(name,gamma)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "unsupported operand type(s) for /: 'float' and 'NoneType'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-c52511e19880>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mforw\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mproblem\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrapper_function\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtemp\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m'noise0'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-3-023332626c52>\u001b[0m in \u001b[0;36mwrapper_function\u001b[0;34m(self, sampled_parameters, noise_key)\u001b[0m\n\u001b[1;32m     36\u001b[0m             \u001b[0mraw_me\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mme\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     37\u001b[0m         \u001b[0;31m#print(me)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 38\u001b[0;31m         \u001b[0mvector\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnoise_models\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mnoise_key\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mloglike_contribution\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mraw_me\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;31m# UL: Problem here. information too much buried\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     39\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_numpy\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvector\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Documents/PhD_Tasks/LeBeDigital/Codes/BayesianInference/bayes/noise.py\u001b[0m in \u001b[0;36mloglike_contribution\u001b[0;34m(self, model_error_dict)\u001b[0m\n\u001b[1;32m     88\u001b[0m         \u001b[0mll\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0.0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     89\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0merror\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mterms\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 90\u001b[0;31m             \u001b[0mll\u001b[0m \u001b[0;34m-=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m2\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mmath\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlog\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mmath\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpi\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0mprec\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     91\u001b[0m             \u001b[0mll\u001b[0m \u001b[0;34m-=\u001b[0m \u001b[0;36m0.5\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mprec\u001b[0m \u001b[0;34m*\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msum\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msquare\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     92\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mll\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for /: 'float' and 'NoneType'"
     ]
    }
   ],
   "source": [
    "forw = problem.wrapper_function(temp,'noise0')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "len(math.pi)/10"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "s1, s2, s3 = MySensor(\"S1\", 0.2), MySensor(\"S2\", 0.5), MySensor(\"S3\", 42.0)\n",
    "\n",
    "fw = MyForwardModel()\n",
    "prm = fw.parameter_list()\n",
    "\n",
    "# set the correct values\n",
    "A_correct = 42.0\n",
    "B_correct = 6174.0\n",
    "prm[\"A\"] = A_correct\n",
    "prm[\"B\"] = B_correct\n",
    "\n",
    "np.random.seed(6174)\n",
    "noise_sd1 = 0.2\n",
    "noise_sd2 = 0.4\n",
    "\n",
    "def generate_data(N_time_steps, noise_sd):\n",
    "    time_steps = np.linspace(0, 1, N_time_steps)\n",
    "    model_response = fw(prm, [s1, s2, s3], time_steps)\n",
    "    sensor_data = {}\n",
    "    for sensor, perfect_data in model_response.items():\n",
    "        sensor_data[sensor] = perfect_data + np.random.normal(\n",
    "            0.0, noise_sd, N_time_steps\n",
    "        )\n",
    "    return time_steps, sensor_data\n",
    "\n",
    "data1 = generate_data(101, noise_sd1)\n",
    "data2 = generate_data(51, noise_sd2)\n",
    "\n",
    "me1 = MyModelError(fw, data1)\n",
    "me2 = MyModelError(fw, data2)\n",
    "\n",
    "problem = PytorchProblem()\n",
    "key1 = problem.add_model_error(me1)\n",
    "key2 = problem.add_model_error(me2)\n",
    "\n",
    "problem.latent[\"A\"].add(me1.parameter_list, \"A\")\n",
    "problem.latent[\"A\"].add(me2.parameter_list, \"A\")\n",
    "# or simply\n",
    "problem.define_shared_latent_parameter_by_name(\"B\")\n",
    "\n",
    "problem.set_normal_prior(\"A\", 40.0, 5.0)\n",
    "problem.set_normal_prior(\"B\", 6000.0, 300.0)\n",
    "\n",
    "noise1 = UncorrelatedNoiseModel()\n",
    "noise1.add(key1, s1)\n",
    "noise1.add(key1, s2)\n",
    "noise1.add(key1, s3)\n",
    "\n",
    "noise2 = UncorrelatedNoiseModel()\n",
    "noise2.add(key2, s1)\n",
    "noise2.add(key2, s2)\n",
    "noise2.add(key2, s3)\n",
    "\n",
    "noise_key1 = problem.add_noise_model(noise1)\n",
    "noise_key2 = problem.add_noise_model(noise2)\n",
    "\n",
    "problem.set_noise_prior(noise_key1, 3 * noise_sd1, sd_shape=0.5)\n",
    "problem.set_noise_prior(noise_key2, 3 * noise_sd2, sd_shape=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "key2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "chk = {}\n",
    "chk['a']=1\n",
    "chk['b']=2\n",
    "chk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ee7fe73ad6ac4db2bf88173e8e30338a",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value='Warmup [1]'), FloatProgress(value=0.0, max=350.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2f9c72b295084536b16bbef7352eb217",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value='Warmup [2]'), FloatProgress(value=0.0, max=350.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "07389c69f86f447f9c591bac6c08a158",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value='Warmup [3]'), FloatProgress(value=0.0, max=350.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "53b48c78f3b944dc942ba23bd823d474",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(HTML(value='Warmup [4]'), FloatProgress(value=0.0, max=350.0), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR LOG CHAIN:0]sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "\n",
      "[ERROR LOG CHAIN:1]sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[ERROR LOG CHAIN:2]sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 101, in run\n",
      "    for sample in _gen_samples(self.kernel, self.warmup_steps, self.num_samples, logging_hook,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\", line 113, in _gen_samples\n",
      "    kernel.setup(warmup_steps, *args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 302, in setup\n",
      "    self._initialize_model_properties(args, kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py\", line 244, in _initialize_model_properties\n",
      "    init_params, potential_fn, transforms, trace = initialize_model(\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 382, in initialize_model\n",
      "    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/util.py\", line 236, in _guess_max_plate_nesting\n",
      "    model_trace = poutine.trace(model).get_trace(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 187, in get_trace\n",
      "    self(*args, **kwargs)\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py\", line 165, in __call__\n",
      "    ret = self.fn(*args, **kwargs)\n",
      "  File \"<ipython-input-4-023332626c52>\", line 24, in posterior_pytorch_model\n",
      "    dist.Normal(self.wrapper_function(sampled_parameters, noise_key),\n",
      "  File \"<ipython-input-4-023332626c52>\", line 38, in wrapper_function\n",
      "    vector = self.noise_models[noise_key].loglike_contribution(raw_me) # UL: Problem here. information too much buried\n",
      "  File \"../bayes/noise.py\", line 91, in loglike_contribution\n",
      "    ll -= 0.5 * prec * np.sum(np.square(error))\n",
      "  File \"<__array_function__ internals>\", line 5, in sum\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 2228, in sum\n",
      "    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,\n",
      "  File \"/home/atul_0711/miniconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py\", line 88, in _wrapreduction\n",
      "    return reduction(axis=axis, out=out, **passkwargs)\n",
      "TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n",
      " * (*, torch.dtype dtype)\n",
      "      didn't match because some of the keywords were incorrect: out, axis\n",
      " * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n",
      " * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
      "\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n * (*, torch.dtype dtype)\n      didn't match because some of the keywords were incorrect: out, axis\n * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-83f681f10fc4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m             \u001b[0mnum_chains\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m             )\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0mmcmc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      8\u001b[0m \u001b[0mmcmc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msummary\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprob\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0.5\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0mposterior_samples\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmcmc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_samples\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/poutine/messenger.py\u001b[0m in \u001b[0;36m_context_wrap\u001b[0;34m(context, fn, *args, **kwargs)\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0m_context_wrap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcontext\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mcontext\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 12\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     13\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    385\u001b[0m             \u001b[0;31m# requires_grad\", which happens with `jit_compile` under PyTorch 1.7\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    386\u001b[0m             \u001b[0margs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0marg\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdetach\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_tensor\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0marg\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32melse\u001b[0m \u001b[0marg\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0marg\u001b[0m \u001b[0;32min\u001b[0m \u001b[0margs\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 387\u001b[0;31m             \u001b[0;32mfor\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mchain_id\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msampler\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    388\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mnum_samples\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mchain_id\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    389\u001b[0m                     \u001b[0mnum_samples\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mchain_id\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/envs/pytorch/lib/python3.8/site-packages/pyro/infer/mcmc/api.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    245\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mval\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    246\u001b[0m                     \u001b[0;31m# Exception trace is already logged by worker.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 247\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mval\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    248\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mval\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    249\u001b[0m                     \u001b[0;32myield\u001b[0m \u001b[0mval\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mchain_id\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:\n * (*, torch.dtype dtype)\n      didn't match because some of the keywords were incorrect: out, axis\n * (tuple of names dim, bool keepdim, *, torch.dtype dtype)\n * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "nuts_kernel = NUTS(problem.posterior_pytorch_model, jit_compile=True)\n",
    "mcmc = MCMC(nuts_kernel,\n",
    "            num_samples=300,\n",
    "            warmup_steps=50,\n",
    "            num_chains=4\n",
    "            )\n",
    "mcmc.run()\n",
    "mcmc.summary(prob=0.5)\n",
    "posterior_samples = mcmc.get_samples()\n",
    "posterior_predictive = Predictive(problem.posterior_pytorch_model, posterior_samples)()\n",
    "prior = Predictive(problem.posterior_pytorch_model, num_samples=500)()\n",
    "pm_data = az.from_pyro(\n",
    "    mcmc,\n",
    "    prior=prior,\n",
    ")\n",
    "fig, axes = plt.subplots(1, 3, figsize=(11, 5), squeeze=False)\n",
    "az.plot_dist_comparison(pm_data, var_names=[\"E\", \"noise0\"], figsize=(8, 9))\n",
    "az.plot_trace(pm_data, figsize=(11, 4))\n",
    "az.plot_pair(pm_data, kind=\"scatter\", ax=axes[0, 0])\n",
    "# az.plot_posterior(pm_data, kind=\"hist\")\n",
    "az.plot_posterior(pm_data, var_names=\"E\", kind=\"hist\", ax=axes[0, 1])\n",
    "az.plot_posterior(pm_data, var_names=\"noise0\", kind=\"hist\", ax=axes[0, 2])\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Pytorch_env",
   "language": "python",
   "name": "pytorch_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
